import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-black text-white px-6 py-4 shadow-md">
          <ul className="flex gap-6">
            <li>
              <a href="/" className="hover:underline">Accueil</a>
            </li>
            <li>
              <a href="/films" className="hover:underline">Films</a>
            </li>
            <li>
              <a href="/ajoutFilm" className="hover:underline">Ajouter un film</a>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
